# File: sample-storage-config.yaml
---
apiVersion: "kadalu-operator.storage/v1alpha1"
kind: "KadaluStorage"
metadata:
  name: "storage-pool-1"
spec:
  type: "Replica2"
  storage:
    # does running kadalu on the controlplane shows instability?
    # - node: pinode1
    #   device: /dev/mmcblk0p3
    - node: pinode2
      device: /dev/mmcblk0p3
    - node: pinode3
      device: /dev/mmcblk0p3
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1
spec:
  storageClassName: kadalu.replica2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
